# Generated by Django 4.2.6 on 2023-10-10 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('email', models.EmailField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('count', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, db_index=True, max_length=50)),
                ('fullDescription', models.CharField(blank=True, max_length=500)),
                ('free_delivery', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reviews', models.ForeignKey(default='not chosen', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.reviews')),
                ('specifications', models.ForeignKey(default='not chosen', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.specifications')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.subcategory')),
                ('tags', models.ForeignKey(default='not chosen', on_delete=django.db.models.deletion.SET_DEFAULT, to='tags.tags')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
