# Generated by Django 4.2.6 on 2023-11-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_sales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="specifications",
                to="product.specifications",
            ),
        ),
    ]
