# Generated by Django 4.2.6 on 2023-11-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0018_alter_product_specifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="specifications",
                to="product.specifications",
            ),
        ),
    ]
