# Generated by Django 4.1.7 on 2023-10-11 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "number",
                    models.CharField(
                        max_length=8,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("01", "01"),
                            ("02", "02"),
                            ("03", "03"),
                            ("04", "04"),
                            ("05", "05"),
                            ("06", "06"),
                            ("07", "07"),
                            ("08", "08"),
                            ("09", "09"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        default=2000,
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxLengthValidator(4),
                        ],
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default="000",
                        max_length=3,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
            ],
        ),
    ]
