# Generated by Django 4.2.6 on 2023-10-11 17:44

from django.db import migrations, models

import auth_custom.models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_custom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=auth_custom.models.avatar
            ),
        ),
    ]
