# Generated by Django 4.2.6 on 2023-10-23 14:50

import django.db.models.deletion
from django.db import migrations, models

import auth_custom.models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_custom", "0002_profile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        blank=True, null=True, upload_to=auth_custom.models.avatar
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=200)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avatar",
                        to="auth_custom.profile",
                    ),
                ),
            ],
        ),
    ]
