# Generated by Django 4.2.6 on 2023-10-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_categoryimage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='catalog.category'),
        ),
    ]
