# Generated by Django 4.2.6 on 2023-10-28 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_categoryimage_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="subcategories",
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.subcategory",
                        verbose_name="Родитель",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="categoryimage",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="catalog.subcategory",
            ),
        ),
    ]
