# Generated by Django 4.2.6 on 2023-10-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_category_product_subcategory'),
        ('catalog', '0005_remove_category_subcategories_subcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
