# Generated by Django 4.2.6 on 2023-10-29 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_remove_product_subcategory_product_category"),
        ("catalog", "0007_remove_subcategory_category_category_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subcategory",
        ),
    ]
