# Generated by Django 4.2.6 on 2023-11-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_order_totalcost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(
                blank=True,
                default="Lenina street, 41, 310 apartment",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(
                blank=True, default="Moscow", max_length=50, null=True
            ),
        ),
    ]
