# Generated by Django 4.2.6 on 2023-11-06 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_order_address_alter_order_city"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="date",
            new_name="createdAt",
        ),
    ]
