# Generated by Django 4.2.6 on 2023-11-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_date_order_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
