# Generated by Django 4.2.6 on 2023-10-29 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="basket_count",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
