# Generated by Django 4.2.6 on 2023-11-01 19:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0015_remove_product_subcategory_product_category'),
        ('basket', '0002_basket_basket_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('cart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basket.testbasket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
