# Generated by Django 4.2.6 on 2023-11-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_itembasket_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='basket_count',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='date',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.AlterField(
            model_name='itembasket',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basket.basket'),
        ),
        migrations.DeleteModel(
            name='TestBasket',
        ),
    ]
